App {
  jdbcUrl = "jdbc:postgresql://localhost:5432/avito"
  jdbcUrl = ${?DB_URL}
  username = "avito"
  username = ${?DB_USER}
  password = "avito"
  password = ${?DB_PASSWORD}
  connectionTimeout = 30000
  maximumPoolSize = 10
}
